
spring:
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html; charset=utf-8
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 1
  profiles:
    active: inte
logging:
  config: classpath:logback-spring.xml