spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Asd104616
    url: jdbc:mysql://101.132.30.161:3306/mtms?useSSL=false&amp;characterEncoding=utf8&amp;characterSetResults=utf8